// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/nuea/go-template/cmd/http/internal/handler"
	"github.com/nuea/go-template/cmd/http/internal/handler/ping"
	"github.com/nuea/go-template/cmd/http/internal/server"
	"github.com/nuea/go-template/internal/config"
	"github.com/nuea/go-template/internal/di"
)

// Injectors from di.go:

func InitContainer() (*Container, func(), error) {
	appConfig := config.ProvideCofig()
	pingHandler := ping.ProvidePingHandler()
	handlers := &handler.Handlers{
		PingHandler: pingHandler,
	}
	httpServer := server.ProvideHTTPServer(appConfig, handlers)
	container := &Container{
		server: httpServer,
	}
	return container, func() {
	}, nil
}

// di.go:

var MainSet = wire.NewSet(di.InternalSet, ProviderSet, handler.HandlerSet, wire.Struct(new(Container), "*"))
